POST http://localhost:8080/events
Content-Type: application/json

{
    "Title": "Birthday",
    "Description": "of my sister",
    "Date": "23/01/2024",
    "Location": "Astana",
    "Capacity": 3,
    "Price": 1000.00,
    "Created_by": 1
}